all:
  vars:
    ansible_user: cisco
    ansible_password: cisco
    ansible_network_os: ios
    ansible_connection: network_cli

  children:
    routers:
      hosts:
        ISP-RTR-A:
          ansible_host: 192.168.1.20
        ISP-RTR-B:
          ansible_host: 192.168.1.21
        CORE-RTR-A:
          ansible_host: 192.168.1.22
        CORE-RTR-B:
          ansible_host: 192.168.1.23

    switches:
      hosts:
        CORE-SW-A:
          ansible_host: 192.168.1.24
        CORE-SW-B:
          ansible_host: 192.168.1.25
        ACCESS-SW1:
          ansible_host: 192.168.1.26
        ACCESS-SW2:
          ansible_host: 192.168.1.27
        ACCESS-SW3:
          ansible_host: 192.168.1.28
          
  