- name: Run show ip interface brief on remote devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Execute show ip interface brief command
      ios_command:
        commands:
          - show ip interface brief
      register: interface_output

    - name: Print output
      debug:
        var: interface_output.stdout_lines
        