- name: Run show running-config on remote devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Execute show running-config command
      ios_command:
        commands:
          - show running-config
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines
        