- name: Run show vlan on remote devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Execute show vlan command
      ios_command:
        commands:
          - show vlan
      register: vlan_output

    - name: Print output
      debug:
        var: vlan_output.stdout_lines
        