- name: Run show version on remote devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Execute show version command
      ios_command:
        commands:
          - show version
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines
        