l2_interfaces:
  - name: Ethernet0/3
    description: access port to VLAN 20
    enabled: true
    mode: access
    vlan: 20

l3_interfaces: []

vlans:
  - id: 10
    name: DATA
  - id: 20
    name: VOICE
  - id: 30
    name: IPTV